### ISSUE TITLE
Error while calling FirebaseCoreForAll.initialize()

### ISSUE THREAD

**Issue by tarang1998** [worldwidee/firebase_for_all#1]
Hello 

This is the error I get while calling the initialize function as mentioned in the docs 

_AssertionError ('package:firebase_core_desktop/firebase_core_desktop.dart': Failed assertion: line 54 pos 7: 'options != null': options should be provided to initialize the default app.)

Any workaround for this 

Thanks :)

**Comment by worldwidee** [comment]
sorry I forgot to update the documentation after the last update. Package will be updated soon <3

**Comment by worldwidee** [comment]
The package has updated now and its repository moved to https://github.com/FlutterWay/firebase_for_all
